bind_addr = ":8080"
log_level = "debug"
database_url = "user=postgres password=postgres host=localhost dbname=postgres sslmode=disable"
session_key = "dfgklhjdgfhduf089hdpf8gud9fg8pdf8hupdf8g9hudpgfb8hudp9f8hudpf"
